"""empty message

Revision ID: 955ed16b3599
Revises: d0b716b98599
Create Date: 2022-10-17 14:55:50.600450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955ed16b3599'
down_revision = 'd0b716b98599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
